language: php
php:
  - '7.4'
before_install:
  - echo 'xdebug.mode=coverage' >> /home/travis/.phpenv/versions/7.4.15/etc/php.ini
install: composer install
after_success:
  - travis_retry php vendor/bin/coveralls
