services:
  Tardigrades\SectionField\Form\Form:
    arguments:
      - '@section_field.manager.doctrine.section_manager'
      - '@section_field.read.section'
      - '@service_container' #created in the SexyFieldFormExtension

  section_field.form: '@Tardigrades\SectionField\Form\Form'

  Tardigrades\Twig\SectionFormTwigExtension:
      arguments:
        - '@section_field.manager.doctrine.section_manager'
        - '@section_field.create.section'
        - '@section_field.form'
        - '@request_stack'
      tags: [ twig.extension ]

  section_field.twig.section_form: '@Tardigrades\Twig\SectionFormTwigExtension'

  HTMLPurifier:
    class: \HTMLPurifier

  Tardigrades\SectionField\Purifier\CacheWarmer\SerializerCacheWarmer:
    public: false
    arguments:
      - [ '%kernel.cache_dir%/htmlpurifier' ]
      - '@HTMLPurifier'
    tags: [ kernel.cache_warmer ]
