services:
#  Tardigrades\SectionField\Purifier\TypeExtension\HTMLPurifierTextTypeExtension:
#    arguments:
#      - '@Tardigrades\SectionField\Purifier\HTMLPurifiersRegistryInterface'
#    tags:
#      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\TextType }

  Tardigrades\SectionField\Purifier\HTMLPurifiersRegistry:
    arguments:
      - '@service_container'

  Tardigrades\SectionField\Form\Form:
    arguments:
      - '@section_field.manager.doctrine.section_manager'
      - '@section_field.read.section'
      - '@Tardigrades\SectionField\Purifier\HTMLPurifiersRegistry'

  section_field.form: '@Tardigrades\SectionField\Form\Form'

  Tardigrades\Twig\SectionFormTwigExtension:
      arguments:
        - '@section_field.manager.doctrine.section_manager'
        - '@section_field.create.section'
        - '@section_field.form'
        - '@request_stack'
      tags: [ twig.extension ]

  section_field.twig.section_form: '@Tardigrades\Twig\SectionFormTwigExtension'

  html.purifier:
    class: 'HTMLPurifier'

  Tardigrades\SectionField\Purifier\CacheWarmer\SerializerCacheWarmer:
    public: false
    arguments:
      - [ '%kernel.cache_dir%/htmlpurifier' ]
      - '@html.purifier'
    tags: [ kernel.cache_warmer ]

  tardigrades_html_purifier.cache_warmer.serializer: '@Tardigrades\SectionField\Purifier\CacheWarmer\SerializerCacheWarmer'

#
#  tardigrades_html_purifier.form.text_type_extension: '@Tardigrades\SectionField\Purifier\TypeExtension\HTMLPurifierTextTypeExtension'
